## Bus Detection and Route Number Recognition

#### Importing necessary Libraries

In [2]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score


In [3]:
folder1=r"Bus"
folder6=r"Negative Images"

## SIFT

#### Extracting SIFT features of the positive Images and appending them into csv

In [4]:
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    resize=(350,350)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('Bus.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (916, 128)
descriptor shape  1  :  (795, 128)
descriptor shape  2  :  (1309, 128)
descriptor shape  3  :  (1737, 128)
descriptor shape  4  :  (1183, 128)
descriptor shape  5  :  (1364, 128)
descriptor shape  6  :  (1742, 128)
descriptor shape  7  :  (1926, 128)
descriptor shape  8  :  (1850, 128)
descriptor shape  9  :  (1593, 128)
descriptor shape  10  :  (796, 128)
descriptor shape  11  :  (1986, 128)
descriptor shape  12  :  (999, 128)
descriptor shape  13  :  (1383, 128)
descriptor shape  14  :  (923, 128)
descriptor shape  15  :  (1182, 128)
descriptor shape  16  :  (1355, 128)
descriptor shape  17  :  (1212, 128)
descriptor shape  18  :  (1288, 128)
descriptor shape  19  :  (1580, 128)
descriptor shape  20  :  (1234, 128)
descriptor shape  21  :  (1306, 128)
descriptor shape  22  :  (1193, 128)
descriptor shape  23  :  (2000, 128)
descriptor shape  24  :  (1449, 128)
descriptor shape  25  :  (972, 128)
descriptor shape  26  :  (1353, 128)
descriptor shape 

In [112]:
data1 = pd.read_csv(r'Bus.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0          1    0    0    4    0    0    0    0    1    4  ...    6    7    0   
1          1    0    0    3   14    0    0    1   14    0  ...   15   15    1   
2         49   45   17   19    2    0    0    1  161   28  ...    2   32    0   
3         35   15   46   81   24    8    1   13  109   36  ...   79  139    1   
4        101  149   32    0    0    0    0    1   33   83  ...    1    7    0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2987446    0    2    1    0    0    0    0    0    4    5  ...   69  106  126   
2987447   57   78   44   38   34   11    2   12    9    6  ...   64   26    2   
2987448    6   17    8   39   26   20   21   10   88  105  ...    5    6   26   
2987449   78   89    2    4    2   43   63   16   95  121  ...    0    1   13   
2987450    0    1   87  115    8    0    0    0   24    5  ...   10   34    6   

         121  122  123  124  125  126  127  
0          3  132  132    2    0    0    0  
1         19   72    5    2    7   19    4  
2          0    0    1    1    1    2    1  
3          0    0    0    0    0   16   10  
4          0    0    2    3    1    0    0  
...      ...  ...  ...  ...  ...  ...  ...  
2987446    3    0    0    0    0   14  101  
2987447   22   31    0    0    0   17    6  
2987448   68  101   30    6    1    0    0  
2987449   18    5   12   27   10    1    2  
2987450   18   15   41   71   73    7    5  

[2987451 rows x 128 columns]

#### Extracting SIFT features of negative Images and appending them into CSV

In [5]:
i=0
for filename in os.listdir(folder6):
    
    path=os.path.join(folder6,filename)
    a=cv2.imread(path)
    resize=(350,350)
    img=cv2.resize(a,resize)
    #resize image
    
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('negative.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (854, 128)
descriptor shape  1  :  (740, 128)
descriptor shape  2  :  (1019, 128)
descriptor shape  3  :  (667, 128)
descriptor shape  4  :  (811, 128)
descriptor shape  5  :  (722, 128)
descriptor shape  6  :  (599, 128)
descriptor shape  7  :  (643, 128)
descriptor shape  8  :  (896, 128)
descriptor shape  9  :  (965, 128)
descriptor shape  10  :  (870, 128)
descriptor shape  11  :  (1038, 128)
descriptor shape  12  :  (920, 128)
descriptor shape  13  :  (1161, 128)
descriptor shape  14  :  (938, 128)
descriptor shape  15  :  (744, 128)
descriptor shape  16  :  (705, 128)
descriptor shape  17  :  (1028, 128)
descriptor shape  18  :  (769, 128)
descriptor shape  19  :  (571, 128)
descriptor shape  20  :  (393, 128)
descriptor shape  21  :  (1067, 128)
descriptor shape  22  :  (563, 128)
descriptor shape  23  :  (643, 128)
descriptor shape  24  :  (1092, 128)
descriptor shape  25  :  (514, 128)
descriptor shape  26  :  (761, 128)
descriptor shape  27  :  (612, 1

In [115]:
data1 = pd.read_csv(r'negative.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         38    1    0    0    0    0    0    2  171    1  ...    0    0   11   
1        101   10    0    0    0    0    0    2  151   19  ...    7   13    4   
2          4    6    0    0    4   75   52   22   16   10  ...    0    1    2   
3         75    0    0    0    0    0    0   18  121    0  ...    3   68   19   
4         44    3    0    0    0    0    0    0  122   26  ...    7   14    0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2269187  137  128    2    0    0    0    0    0  110   92  ...    0    0    5   
2269188  104   14    0    0    0    0    0    5  190   27  ...    2    4    0   
2269189  111   24    2    0    0    0    0    4  197   29  ...    0   10    0   
2269190   32  125   42    4    3    4   23   39  158  168  ...    0    5    1   
2269191   99  123    3    0    0    0    5   32  175  122  ...   28   28    0   

         121  122  123  124  125  126  127  
0          3    4   10   85    9    0    0  
1         16   29   25   15    3    3    4  
2          1    8   84   47   21    0    3  
3         13   38  121  121   12    6   21  
4          1   13   77  125   14    2    0  
...      ...  ...  ...  ...  ...  ...  ...  
2269187   22   28   14    2    0    0    0  
2269188    0    0    0    1    1    0    0  
2269189    0    0    0    1    0    0    0  
2269190    0    0    1    0    0    0    0  
2269191    0    0    0    0    0    0    0  

[2269192 rows x 128 columns]

In [6]:
from sklearn.preprocessing import StandardScaler

data1 = pd.read_csv(r'Bus.csv',header=None,dtype='uint8')
sc = StandardScaler()
data1=data1.astype(np.uint8) 
data1 = sc.fit_transform(data1)
data1 = pd.DataFrame(data1)
 
data2= pd.read_csv(r'negative.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2 = sc.fit_transform(data2)
data2= pd.DataFrame(data2)

data=data1.append(data2)
csv_data=data.to_csv('bus_neagtive_mix.csv', mode='a', header=False,index=False)

## K-Means

In [7]:
kmeans = KMeans(n_clusters=7)
kmeans.fit(data)

KMeans(n_clusters=7)

In [8]:
import pickle
filename = 'Kmeans_CL_9_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5,6,7])
print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([ 675356,  710464,  643790,  704586,  787612,  699611, 1180528],
      dtype=int64), array([0, 1, 2, 3, 4, 5, 6, 7])) 



#### Performing K-Means prediction on the entire Bus dataset with the pretrained K-Means model then normalizing the histogram bins using MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
i=0
data=[]

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
 
    #gray image
    gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7])
    hist=scaler.fit_transform(hist[0].reshape((-1,1)))
    #append the dataframe into the array in append mode
    data.append(hist)
data=np.array(data) 
data=data.reshape(3009,7)

#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)

#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('final_bus.csv', mode='a',header=False,index=False)

#### Performing K-Means prediction on all the Negative images with the pretrained K-Means model then normalizing the histogram bins using MinMaxScaler

In [10]:
i=1
data=[]
k=0
folder6=r"Negative Images"
for filename in os.listdir(folder6):
    path=os.path.join(folder6,filename)
    a=cv2.imread(path)
   
    gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    array_double = np.array(out, dtype=np.double)
    
    a=kmeans.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7])
    hist=scaler.fit_transform(hist[0].reshape((-1,1)))
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist)
data=np.array(data) 
data=data.reshape(3056,7)

#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)

#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('final_nbus.csv', mode='a',header=False,index=False)

In [11]:
print("Bus")
dat1= pd.read_csv(r'final_bus.csv',header=None)
print(dat1)

Bus
             0         1         2         3         4         5         6  7
0     0.000000  0.195489  0.015038  0.315789  0.195489  0.112782  1.000000  0
1     0.052632  0.000000  0.828947  1.000000  0.013158  0.013158  0.355263  0
2     0.000000  0.461078  0.628743  1.000000  0.239521  0.287425  0.526946  0
3     0.000000  0.156463  0.340136  1.000000  0.074830  0.122449  0.789116  0
4     0.154412  0.073529  0.242647  0.566176  0.000000  0.022059  1.000000  0
...        ...       ...       ...       ...       ...       ...       ... ..
3004  0.000000  0.112069  0.568966  1.000000  0.017241  0.034483  0.715517  0
3005  0.733333  0.753846  0.302564  0.635897  1.000000  0.697436  0.000000  0
3006  0.000000  0.096774  0.304147  0.258065  0.161290  0.105991  1.000000  0
3007  0.220339  0.254237  1.000000  0.881356  0.000000  0.152542  0.779661  0
3008  0.000000  0.705882  0.568627  0.882353  0.843137  0.705882  1.000000  0

[3009 rows x 8 columns]


In [12]:
print("Non-Bus")
dat2= pd.read_csv(r'final_nbus.csv',header=None)
print(dat2)

Non-Bus
             0         1         2         3         4         5         6  7
0     0.517241  0.275862  0.000000  0.379310  1.000000  0.931034  0.758621  1
1     0.966102  0.830508  0.000000  0.101695  1.000000  0.694915  0.525424  1
2     0.380435  0.478261  0.652174  0.000000  1.000000  0.597826  0.739130  1
3     0.116279  0.325581  0.000000  0.081395  0.558140  0.383721  1.000000  1
4     0.193548  0.274194  0.032258  0.193548  0.887097  0.000000  1.000000  1
...        ...       ...       ...       ...       ...       ...       ... ..
3051  0.000000  0.542857  0.085714  0.257143  0.342857  0.514286  1.000000  1
3052  0.649485  0.680412  0.567010  0.000000  0.701031  1.000000  0.515464  1
3053  0.370787  0.157303  0.539326  0.000000  0.483146  0.460674  1.000000  1
3054  0.671053  0.723684  0.000000  0.394737  1.000000  0.631579  0.460526  1
3055  0.942308  0.826923  0.000000  0.230769  1.000000  0.807692  0.846154  1

[3056 rows x 8 columns]


In [13]:
dat1= pd.read_csv(r'final_bus.csv',header=None)
dat2= pd.read_csv(r'final_nbus.csv',header=None)
A=dat1.append(dat2)
print (A)

csv_data=A.to_csv('final_all.csv', mode='a',header=False,index=False)

             0         1         2         3         4         5         6  7
0     0.000000  0.195489  0.015038  0.315789  0.195489  0.112782  1.000000  0
1     0.052632  0.000000  0.828947  1.000000  0.013158  0.013158  0.355263  0
2     0.000000  0.461078  0.628743  1.000000  0.239521  0.287425  0.526946  0
3     0.000000  0.156463  0.340136  1.000000  0.074830  0.122449  0.789116  0
4     0.154412  0.073529  0.242647  0.566176  0.000000  0.022059  1.000000  0
...        ...       ...       ...       ...       ...       ...       ... ..
3051  0.000000  0.542857  0.085714  0.257143  0.342857  0.514286  1.000000  1
3052  0.649485  0.680412  0.567010  0.000000  0.701031  1.000000  0.515464  1
3053  0.370787  0.157303  0.539326  0.000000  0.483146  0.460674  1.000000  1
3054  0.671053  0.723684  0.000000  0.394737  1.000000  0.631579  0.460526  1
3055  0.942308  0.826923  0.000000  0.230769  1.000000  0.807692  0.846154  1

[6065 rows x 8 columns]


In [16]:
x = A.iloc[:,0:7].values
x

array([[0.        , 0.19548872, 0.01503759, ..., 0.19548872, 0.11278195,
        1.        ],
       [0.05263158, 0.        , 0.82894737, ..., 0.01315789, 0.01315789,
        0.35526316],
       [0.        , 0.46107784, 0.62874251, ..., 0.23952096, 0.28742515,
        0.52694611],
       ...,
       [0.37078652, 0.15730337, 0.53932584, ..., 0.48314607, 0.46067416,
        1.        ],
       [0.67105263, 0.72368421, 0.        , ..., 1.        , 0.63157895,
        0.46052632],
       [0.94230769, 0.82692308, 0.        , ..., 1.        , 0.80769231,
        0.84615385]])

In [18]:
y = A.iloc[:,7].values
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [19]:
from sklearn.preprocessing import StandardScaler
BusS = StandardScaler()
Bus = BusS.fit_transform(x)

In [20]:
Bus

array([[-0.98678112, -0.68239632, -0.93076505, ..., -0.75491634,
        -0.96856513,  0.72022269],
       [-0.8129791 , -1.37750481,  1.65344423, ..., -1.24955407,
        -1.30602751, -1.26822256],
       [-0.98678112,  0.26197148,  1.01778257, ..., -0.63546311,
        -0.37698606, -0.73873189],
       ...,
       [ 0.2376443 , -0.81817378,  0.73387961, ...,  0.02545733,
         0.20987039,  0.72022269],
       [ 1.22919454,  1.19573334, -0.97851026, ...,  1.4276089 ,
         0.78878614, -0.94357844],
       [ 2.12494338,  1.56282466, -0.97851026, ...,  1.4276089 ,
         1.38534519,  0.24574282]])

## PCA

In [22]:
from sklearn.decomposition import PCA

pca = PCA(n_components=None)
pca.fit(Bus)

PCA()

In [24]:
Bus1= pca.transform(Bus)
Bus1

array([[-1.22997379, -1.42956524, -0.46312218, ..., -0.74495835,
        -0.21199509, -0.08224116],
       [-2.8136938 ,  1.94916942, -0.78814509, ..., -0.06837971,
         0.11309171,  0.35816999],
       [-1.4151616 ,  1.70965692,  0.44175226, ..., -0.41932024,
        -0.38219227, -0.15262903],
       ...,
       [-0.15491011, -0.91845649,  0.21823697, ...,  0.6873682 ,
         0.62141101,  0.21612429],
       [ 2.58905831,  0.55703118, -0.42660492, ..., -0.0053197 ,
        -0.29255749, -0.19830196],
       [ 3.29311903, -0.31070322,  0.32719259, ...,  0.93047204,
        -0.08122432,  0.17960559]])

In [26]:
Bus1 = pd.DataFrame(Bus1)
Bus1

0         1         2         3         4         5         6
0    -1.229974 -1.429565 -0.463122 -0.288206 -0.744958 -0.211995 -0.082241
1    -2.813694  1.949169 -0.788145  0.335341 -0.068380  0.113092  0.358170
2    -1.415162  1.709657  0.441752 -0.362838 -0.419320 -0.382192 -0.152629
3    -2.186147  0.489789 -0.327989 -0.942715 -0.312578  0.012621 -0.156966
4    -2.002568 -0.829717 -0.598450 -0.460396  0.007479 -0.034643  0.402991
...        ...       ...       ...       ...       ...       ...       ...
6060  0.038213 -1.033899  0.872190 -0.268146 -0.943922 -0.114540 -0.205027
6061  2.365351  0.714676  1.089102  1.187084  0.246306  0.703739  0.718686
6062 -0.154910 -0.918456  0.218237  1.245474  0.687368  0.621411  0.216124
6063  2.589058  0.557031 -0.426605 -0.383538 -0.005320 -0.292557 -0.198302
6064  3.293119 -0.310703  0.327193 -0.579263  0.930472 -0.081224  0.179606

[6065 rows x 7 columns]

In [27]:
Bus1.shape

(6065, 7)

In [28]:
print(pca.explained_variance_ratio_) 

[0.50999961 0.19362175 0.0968234  0.07148154 0.05624901 0.03751173
 0.03431296]


In [47]:
pca = PCA(n_components=4)
pca.fit(Bus)

PCA(n_components=4)

In [48]:
filename = 'PCA_4_Model.sav'
pickle.dump(pca, open(filename, 'wb'))

In [50]:
Bus1 = pca.transform(Bus)
Bus1

array([[-1.22997379, -1.42956524, -0.46312218, -0.28820644],
       [-2.8136938 ,  1.94916942, -0.78814509,  0.33534108],
       [-1.4151616 ,  1.70965692,  0.44175226, -0.36283821],
       ...,
       [-0.15491011, -0.91845649,  0.21823697,  1.24547353],
       [ 2.58905831,  0.55703118, -0.42660492, -0.38353841],
       [ 3.29311903, -0.31070322,  0.32719259, -0.57926289]])

In [51]:
Bus1.shape

(6065, 4)

In [52]:
print(pca.explained_variance_ratio_) 

[0.50999961 0.19362175 0.0968234  0.07148154]


In [54]:
Bus1 = pd.DataFrame(Bus1)
Bus1

0         1         2         3
0    -1.229974 -1.429565 -0.463122 -0.288206
1    -2.813694  1.949169 -0.788145  0.335341
2    -1.415162  1.709657  0.441752 -0.362838
3    -2.186147  0.489789 -0.327989 -0.942715
4    -2.002568 -0.829717 -0.598450 -0.460396
...        ...       ...       ...       ...
6060  0.038213 -1.033899  0.872190 -0.268146
6061  2.365351  0.714676  1.089102  1.187084
6062 -0.154910 -0.918456  0.218237  1.245474
6063  2.589058  0.557031 -0.426605 -0.383538
6064  3.293119 -0.310703  0.327193 -0.579263

[6065 rows x 4 columns]

In [56]:
B=pd.concat([Bus1, pd.DataFrame(y)],axis=1)
B

0         1         2         3  3
0    -1.229974 -1.429565 -0.463122 -0.288206  0
1    -2.813694  1.949169 -0.788145  0.335341  0
2    -1.415162  1.709657  0.441752 -0.362838  0
3    -2.186147  0.489789 -0.327989 -0.942715  0
4    -2.002568 -0.829717 -0.598450 -0.460396  0
...        ...       ...       ...       ... ..
6060  0.038213 -1.033899  0.872190 -0.268146  1
6061  2.365351  0.714676  1.089102  1.187084  1
6062 -0.154910 -0.918456  0.218237  1.245474  1
6063  2.589058  0.557031 -0.426605 -0.383538  1
6064  3.293119 -0.310703  0.327193 -0.579263  1

[6065 rows x 5 columns]

In [57]:
csv_data=B.to_csv('final_final.csv', mode='a',header=False,index=False)

In [58]:
data= pd.read_csv(r'Final_final.csv',header=None)
data

0         1         2         3  4
0    -1.229974 -1.429565 -0.463122 -0.288206  0
1    -2.813694  1.949169 -0.788145  0.335341  0
2    -1.415162  1.709657  0.441752 -0.362838  0
3    -2.186147  0.489789 -0.327989 -0.942715  0
4    -2.002568 -0.829717 -0.598450 -0.460396  0
...        ...       ...       ...       ... ..
6060  0.038213 -1.033899  0.872190 -0.268146  1
6061  2.365351  0.714676  1.089102  1.187084  1
6062 -0.154910 -0.918456  0.218237  1.245474  1
6063  2.589058  0.557031 -0.426605 -0.383538  1
6064  3.293119 -0.310703  0.327193 -0.579263  1

[6065 rows x 5 columns]

In [59]:
x = data.iloc[:,0:4].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,4]
print("Y values")
print(y)

X values
[[-1.22997379 -1.42956524 -0.46312218 -0.28820644]
 [-2.8136938   1.94916942 -0.78814509  0.33534108]
 [-1.4151616   1.70965692  0.44175226 -0.36283821]
 ...
 [-0.15491011 -0.91845649  0.21823697  1.24547353]
 [ 2.58905831  0.55703118 -0.42660492 -0.38353841]
 [ 3.29311903 -0.31070322  0.32719259 -0.57926289]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
6060    1
6061    1
6062    1
6063    1
6064    1
Name: 4, Length: 6065, dtype: int64


#### Partitioning the data

In [60]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

## Classifiers

#### 1. Decision Tree 

In [61]:
from sklearn.metrics import accuracy_score

#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = 'model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))

#training the model with the Training Variables 
model1.fit(x_train, y_train)

#predicting the traget variable using testing variables
y_pred = model1.predict(x_test)

#Results
print("Decision Tree Results")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))
# calculate the sensitivity
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred) 
print ("Confusion Matrix : \n", cm)

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
conf_sensitivity = (TP / float(TP + FN))

#calculate the specificity
conf_specificity = (TN / float(TN + FP))
print(conf_sensitivity)
print(conf_specificity)
print("F1 score:",metrics.f1_score(y_test, y_pred))

Decision Tree Results
Precision: 0.824390243902439
Recall: 0.8297872340425532
Confusion Matrix : 
 [[494 108]
 [104 507]]
Accuracy :  0.8252267106347898
0.8297872340425532
0.8205980066445183
F1 score: 0.8270799347471451


##### Testing Decison Tree

In [63]:
r_dt=[]
folder10=r"Test"
for filename in os.listdir(folder10):
    #path
    path=os.path.join(folder10,filename)
    a=cv2.imread(path)
    resize=(350,350)
    img=cv2.resize(a,resize)
    data=[]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)

    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)

    #get the values of the histogram for one image 
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the hostogram for all those vlaues
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7])
    hist=scaler.fit_transform(hist[0].reshape((-1,1)))
    
    #append the dataframe into the array in append mode
    data.append(hist)
    data=np.array(data)
    data=data.reshape(1,7)
    Output = pd.DataFrame(data)
   
    from sklearn.preprocessing import StandardScaler
    MuktaS = StandardScaler()
    Mukta = MuktaS.fit_transform(Output)
    MB = pca.transform(Mukta)
    y_pred_dt = model1.predict(MB)
    r_dt.append(y_pred_dt)

#### 2. Random Forest 

In [64]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

# calculate the sensitivity
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
conf_sensitivity = (TP / float(TP + FN))

#calculate the specificity
conf_specificity = (TN / float(TN + FP))
print(conf_sensitivity)
print(conf_specificity)
print("F1 score:",metrics.f1_score(y_test, y_pred))

Precision: 0.8683760683760684
Recall: 0.8314238952536824
Confusion Matrix : 
 [[525  77]
 [103 508]]
Accuracy :  0.8516075845012366
0.8314238952536824
0.872093023255814
F1 score: 0.8494983277591973


##### Testing Random forest

In [65]:
r_rf=[]
folder10=r"Test"
for filename in os.listdir(folder10):
    #path
    path=os.path.join(folder10,filename)
    a=cv2.imread(path)
    resize=(350,350)
    img=cv2.resize(a,resize)
    data=[]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)

    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)

    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)

    #get the values of the histogram for one image
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the hostogram for all those vlaues
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7])
    hist=scaler.fit_transform(hist[0].reshape((-1,1)))
    
    #append the dataframe into the array in append mode
    data.append(hist)
    data=np.array(data)
    data=data.reshape(1,7)

    Output = pd.DataFrame(data)
    
    from sklearn.preprocessing import StandardScaler
    MuktaS = StandardScaler()
    Mukta = MuktaS.fit_transform(Output)
    MB = pca.transform(Mukta)
    y_pred_rf = clf.predict(MB)
    r_rf.append(y_pred_rf)

#### 3. K-Nearest Neighbours

In [66]:
from sklearn.neighbors import KNeighborsClassifier 

classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train)

#Predicting the test set result  
y_pred= classifier.predict(x_test)
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

# calculate the sensitivity
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
conf_sensitivity = (TP / float(TP + FN))

#calculate the specificity
conf_specificity = (TN / float(TN + FP))
print(conf_sensitivity)
print(conf_specificity)
print("F1 score:",metrics.f1_score(y_test, y_pred))

r_kn=[]
folder10=r"Test"
for filename in os.listdir(folder10):
    #path
    path=os.path.join(folder10,filename)
    a=cv2.imread(path)
    resize=(350,350)
    img=cv2.resize(a,resize)
    data=[]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)

    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)

    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)

    #get the values of the histogram for one image 
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the hostogram for all those vlaues
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7])
    hist=scaler.fit_transform(hist[0].reshape((-1,1)))
    
    #append the dataframe into the array in append mode
    data.append(hist)
    data=np.array(data)
    data=data.reshape(1,7)

    Output = pd.DataFrame(data)
    
    from sklearn.preprocessing import StandardScaler
    MuktaS = StandardScaler()
    Mukta = MuktaS.fit_transform(Output)
    MB = pca.transform(Mukta)
    y_pred_kn = classifier.predict(MB)
    r_kn.append(y_pred_kn)

Precision: 0.8620102214650767
Recall: 0.8281505728314239
Confusion Matrix : 
 [[521  81]
 [105 506]]
Accuracy :  0.8466611706512778
0.8281505728314239
0.8654485049833887
F1 score: 0.8447412353923205


#### 4. SVM 

In [67]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

# calculate the sensitivity
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
conf_sensitivity = (TP / float(TP + FN))

#calculate the specificity
conf_specificity = (TN / float(TN + FP))
print(conf_sensitivity)
print(conf_specificity)
print("F1 score:",metrics.f1_score(y_test, y_pred))

Precision: 0.8628099173553719
Recall: 0.8543371522094927
Confusion Matrix : 
 [[519  83]
 [ 89 522]]
Accuracy :  0.8582028029678483
0.8543371522094927
0.8621262458471761
F1 score: 0.8585526315789473


##### Testing SVM

In [68]:
r_sv=[]
folder10=r"Test"
for filename in os.listdir(folder10):
    #path
    path=os.path.join(folder10,filename)
    a=cv2.imread(path)
    resize=(350,350)
    img=cv2.resize(a,resize)
    data=[]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)

    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)

    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)

    #get the values of the histogram for one image
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the hostogram for all those vlaues
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7])
    hist=scaler.fit_transform(hist[0].reshape((-1,1)))
    #append the dataframe into the array in append mode
    data.append(hist)
    data=np.array(data)
    data=data.reshape(1,7)

    Output = pd.DataFrame(data)
    
    from sklearn.preprocessing import StandardScaler
    MuktaS = StandardScaler()
    Mukta = MuktaS.fit_transform(Output)
    MB = pca.transform(Mukta)
    y_pred_sv = clf.predict(MB)
    r_sv.append(y_pred_sv)

#### 5. Logistic Regression 

In [69]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
print(y_pred)
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

# calculate the sensitivity
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
conf_sensitivity = (TP / float(TP + FN))

#calculate the specificity
conf_specificity = (TN / float(TN + FP))
print(conf_sensitivity)
print(conf_specificity)
print("F1 score:",metrics.f1_score(y_test, y_pred))


r_logi=[]
folder10=r"Test"
for filename in os.listdir(folder10):
    #path
    path=os.path.join(folder10,filename)
    a=cv2.imread(path)
    resize=(350,350)
    img=cv2.resize(a,resize)
    data=[]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)

    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)

    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)

    #get the values of the histogram for one image 
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the hostogram for all those vlaues
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7])
    hist=scaler.fit_transform(hist[0].reshape((-1,1)))
    #append the dataframe into the array in append mode
    data.append(hist)
    data=np.array(data)
    data=data.reshape(1,7)
    #append the dataframe into the array in append mode
    Output = pd.DataFrame(data)
 
    from sklearn.preprocessing import StandardScaler
    MuktaS = StandardScaler()
    Mukta = MuktaS.fit_transform(Output)
    MB = pca.transform(Mukta)
    y_pred_logi = classifier.predict(MB)
    r_logi.append(y_pred_logi)

[1 0 0 ... 0 1 0]
Precision: 0.8618421052631579
Recall: 0.8576104746317512
Confusion Matrix : 
 [[518  84]
 [ 87 524]]
Accuracy :  0.8590272052761748
0.8576104746317512
0.8604651162790697
F1 score: 0.8597210828547991


In [72]:
test_results=pd.DataFrame()
test_results["Desicion Tree"]=r_dt
print(test_results)
test_results["K-NN"]=r_kn
test_results["SVM"]=r_sv
test_results["Logistic Regression"]=r_logi
test_results["Random_Forest"]=r_rf
print(test_results)

     Desicion Tree
0              [1]
1              [1]
2              [1]
3              [1]
4              [1]
...            ...
1195           [1]
1196           [1]
1197           [1]
1198           [1]
1199           [1]

[1200 rows x 1 columns]
     Desicion Tree K-NN  SVM Logistic Regression Random_Forest
0              [1]  [0]  [0]                 [1]           [0]
1              [1]  [0]  [0]                 [1]           [0]
2              [1]  [0]  [0]                 [1]           [0]
3              [1]  [0]  [0]                 [1]           [0]
4              [1]  [0]  [0]                 [1]           [0]
...            ...  ...  ...                 ...           ...
1195           [1]  [0]  [0]                 [1]           [0]
1196           [1]  [0]  [0]                 [1]           [0]
1197           [1]  [0]  [0]                 [1]           [0]
1198           [1]  [0]  [0]                 [1]           [0]
1199           [1]  [0]  [0]                 [1]      

In [73]:
csv_data=test_results.to_csv('Results.csv', mode='w', header=True,index=True)

## OCR

In [6]:
import cv2
import numpy as np
img = cv2.imread('16.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
lower_red = np.array([0,50,50])
upper_red = np.array([10,255,255])
mask0 = cv2.inRange(img, lower_red, upper_red)

# upper mask (170-180)
lower_red = np.array([170,50,50])
upper_red = np.array([180,255,255])
mask1 = cv2.inRange(img, lower_red, upper_red)

# join my masks
mask = mask0+mask1

kernel = np.ones((3,3),np.uint8)
opening = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
cv2.imwrite('mask.jpg',opening)

True

In [3]:
!pip install pytesseract

  Using cached https://files.pythonhosted.org/packages/a3/c9/d6e8903482bd6fb994c32722831d15842dd8b614f94ad9ca735807252671/pytesseract-0.3.8.tar.gz
  Stored in directory: C:\Users\ANUSHA AGRAWAL\AppData\Local\pip\Cache\wheels\a2\66\45\88bf1b2d428817a006944b9730b27d6861b776e05a9e262bd4
Successfully built pytesseract


In [7]:
import cv2
import pytesseract
pytesseract.pytesseract.tesseract_cmd=r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe' #put your path
img = cv2.imread("mask.jpg")
img = cv2.resize(img, (400, 450))
cv2.imshow("Image", img)
text = pytesseract.image_to_string(img)
print(text)
cv2.waitKey(0)
cv2.destroyAllWindows()

12

